[theme]
primaryColor = "#00d4aa"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "monospace"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false
